<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getRecentArticles($numberOfArticles){
        $qb = $this->createQueryBuilder('a');
        $qb ->select('a')
            ->orderBy('a.createdAt', 'desc')
            ->setMaxResults($numberOfArticles);
        return $qb->getQuery()->getResult();
    }
}
