<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getLastComments($numberOfComments){
        return $this->findBy(
            array(),
            array('createdAt' => 'DESC'),
            $numberOfComments,
            0
        );
    }
}
