<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function getTagList(){
        $qb = $this->createQueryBuilder('t')
            ->select('t.id, t.tagName, COUNT(a.id) as numberOfArticles')
            ->join('t.articles','a')
            ->addGroupBy('t.id');

        return $qb->getQuery()->getArrayResult();
    }
}
