app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin_logout:
    path: /admin/logout

admin_login_check:
    path: /admin/login_check

author_logout:
    path: /author/logout

author_login_check:
    path: /author/login_check