app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin_login_check:
    path: /admin/login_check

admin_logout:
    path: /admin/logout

author_login_check:
  path: /author/login_check

author_logout:
  path: /author/logout
