# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
              users:
                  admin:
                      password: admin
                      roles: ROLE_ADMIN

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Sécurisation de la route /admin avec une authentification par formulaire
        admin:
            pattern: ^/admin
            provider: in_memory
            form_login:
              login_path: admin_login
              check_path: admin_login_check
              default_target_path: /admin
            logout:
              path: admin_logout
              target: /

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    # Définit l'encodage des mots de passe
    # ici texte brut (mauvaise idée en production)
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    access_control:
        # seuls les administrateurs peuvent créer de nouveaux auteurs
        - { path: ^/author/new, roles: ROLE_ADMIN }