# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\Author:
          algorithm: sha1
          iterations: 1
          encode_as_base64: false

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
              users:
                admin:
                  password: 123
                  roles: ROLE_ADMIN
                god:
                  password: 456
                  roles: ROLE_SUPER_ADMIN

        author_provider:
            entity:
                class: AppBundle:Author
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: in_memory
            form_login:
              login_path: admin_login
              check_path: admin_login_check
              default_target_path: admin_home
            logout:
              path: admin_logout
              target: homepage

        author:
            pattern: ^/author
            provider: author_provider
            form_login:
              login_path: author_login
              check_path: author_login_check
              default_target_path: author_home
            logout:
              path: author_logout
              target: homepage

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    role_hierarchy:
      ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
      - {path: ^/admin, roles: ROLE_ADMIN}
      - {path: ^/author, roles: ROLE_AUTHOR}