services:
  data_provider:
    class: AppBundle\Services\FakeDataProvider


  app.form.type.article:
    class: AppBundle\Form\ArticleType
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: form.type }


  app.form.data_transformer.article:
    class: AppBundle\Form\DataTransformer\EntityToIntDataTransformer
    arguments:
      - "@doctrine.orm.entity_manager"
      - "AppBundle\\Entity\\Article"
      - "AppBundle:Article"

  app.form.type.comment:
      class: AppBundle\Form\CommentType
      arguments: ["@app.form.data_transformer.article"]
      tags:
        - { name: form.type}

  app.form.comment:
    factory_service: form.factory
    factory_method: create
    class: Symfony\Component\Form\Form
    arguments:
      - "@app.form.type.comment"


  app.formhandler.comment:
    class: AppBundle\Form\FormHandler\CommentFormHandler
    arguments:
      - "@app.form.comment"
      - "@request_stack"
      - "@doctrine.orm.entity_manager"
    scope: request
